
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        username: admin
        password: hyundai
        url: jdbc:postgresql://localhost:5432/astue
    jpa:
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                      dialect: org.hibernate.dialect.PostgreSQLDialect
                      ddl-auto: none
                      
logging:
  pattern:
      console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint}"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
                        
  level:
        astue: TRACE
              
                      
    
server:
  port: 8080 
    
        
                   
---

spring:
    config:
        activate:
            on-profile: test

    datasource:
        username: admin
        password: hyundai
        url: jdbc:postgresql://localhost:5432/astue
    jpa:
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                      dialect: org.hibernate.dialect.PostgreSQLDialect
                      ddl-auto: none
                      
logging:
  pattern:
      console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint}"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
                        
  level:
        astue: TRACE
              
                      
    
server:
  port: 8080 
                
            
            
---
spring:
    config:
        activate:
            on-profile: prod